blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'post_list'),
    path('detail/<int:pk>', views.PostDetail.as_view(), name = "post_detail"),
    path('create/', views.PostCreate.as_view(), name = "post_create"),
    path('update/<int:pk>', views.PostUpdate.as_view(), name = "post_update"),
    path('delete/<int:pk>', views.PostDelete.as_view(), name = "post_delete"),
    path('my-post-lists', views.MyPostList.as_view(), name = 'my_post_list')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('followers/', include('followers.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path("detail/<int:pk>", views.UserProfile.as_view(), name = 'profile_detail'),
    path("update/<int:pk>", views.UpdateUserProfile.as_view(), name = 'profile_update'),
    # Update Profile Picture
    path("update/picture/<int:pk>", views.UpdateProfilePicture, name = 'picture_update'),
    # Delete Profile Picture
    path("delete/picture/<int:pk>", views.DeleteProfilePicture, name = 'picture_delete'),
    # For Followers
    path('detail/<int:pk>/follow/', views.FollowView.as_view(), name = 'follow'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.dispatch import receiver
from django.db.models.signals import post_save

# Model for User Profiles
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profiles')
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.TextField(blank=True)
    mobile = models.CharField(max_length=16, blank=True)
    image = ImageField(upload_to="profiles", blank=True)

    def __str__(self):
        return self.user.username
    
# Signal for Creating a User Profile when we sign up
@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

# Signal for Updating a User Profile when we update User Model
@receiver(post_save, sender = User)
def save_user_profile(sender, instance, **kwargs):
    instance.profiles.save()

profiles/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, View
from profiles.models import Profile
from django.contrib.auth.models import User
import os
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.models import Post
from followers.models import Follower
from django.http import JsonResponse, HttpResponseBadRequest

# User Profile Detail View
class UserProfile(DetailView):
    model = Profile
    # context_object_name = 'profile'
    # template_name = 'profiles/profile_detail.html'
    
    # def get_queryset(self):
    #     userId = User.objects.filter(id = self.kwargs['pk'])
    #     print(userId[0].profiles.id)
    #     queryset = self.model.objects.filter(id = userId[0].profiles.id)
    #     return queryset

    def get_context_data(self, **kwargs):
        user = self.get_object()
        owner_id = User.objects.filter(username=user)[0].id
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(owner=owner_id).count()
        context['total_followers'] = Follower.objects.filter(following=owner_id).count()

        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=owner_id, followed_by=self.request.user).exists()
        return context

# Update User Profile
class UpdateUserProfile(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['first_name','last_name', 'mobile', 'address']

    def get_success_url(self):
        return reverse_lazy('profiles:profile_detail', kwargs={'pk' : self.kwargs['pk']})

# Update Profile Picture
def UpdateProfilePicture(request, pk):
    profile = Profile.objects.get(id=pk)
    if request.method == "POST":
        if len(request.FILES) != 0:
            if profile.image:
                os.remove(profile.image.path)
            profile.image = request.FILES['image_document']
        profile.save()
        success_url = '/profile/detail/' + str(profile.id)
        return redirect(success_url)
    context = {'profile':profile}
    return render(request, 'profiles/picture_form.html', context)

# Remove Profile Picture
def DeleteProfilePicture(request, pk):
    profile = Profile.objects.get(id=pk)
    os.remove(profile.image.path)
    profile.image=""
    profile.save()
    success_url = '/profile/detail/' + str(profile.id)
    return redirect(success_url)

class FollowView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "id" not in data:
            return HttpResponseBadRequest("Missing action or id")
        
        try:
            other_user = User.objects.get(id=data["id"])
        except:
            return HttpResponseBadRequest("User not found")
        
        if data['action'] == 'follow':
            # follow
            follower, created = Follower.objects.get_or_create(followed_by=request.user, following=other_user)
        else:
            # un-follow
            try:
                follower, created = Follower.objects.get_or_create(followed_by=request.user, following=other_user)
            except:
                follower = None

            if follower:
                follower.delete()

        json_data = {
            'success' : True,
            'wording' : 'Unfollow' if data['action'] == 'follow' else 'Follow',
        }

        return JsonResponse(json_data)

profiles/templates/profiles/picture_form.html
{% extends 'base_master.html' %}

{% block title %}
    Tech Blog - Update Profile
{% endblock title %}
    
{% block content %}
    <div class="container mt-3">
        <h1>Upload Profile Picture</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <input class="form-control" type="file" title="profile_picture" 
                    name="image_document" required>
            </div>
            
            <button class="btn btn-outline-primary" type="submit">Upload</button>
            <a class="btn btn-outline-danger" 
                href="{% url 'profiles:profile_detail' profile.id %}">Cancel</a>
        </form>
    </div>
{% endblock content %}

profiles/templates/profiles/profile_detail.html
<!-- Template: https://mdbootstrap.com/docs/standard/extended/profiles/ -->

{% extends 'base_master.html' %}
{% load thumbnail %}
{% load static %}

{% block title %}
    {% if not user.is_authenticated or profile.user != user %}
      {{profile.first_name}}'s Profile
    {% else %}          
      Edit User Profile
    {% endif %}
{% endblock title %}

{% block content %}
    <section>
        <div class="container">

          {% if not user.is_authenticated or profile.user != user %}
            <h1>{{profile.first_name}}'s Profile</h1>
          {% else %}          
            <h1>Edit User Profile</h1>
          {% endif %}
        
          <div class="row">
            <div class="col-lg-4">
              <div class="card mb-4">
                <div class="card-body text-center">
                    {% if profile.image %}
                        {% thumbnail profile.image "200x200" crop="center" as im %}
                            <img class="rounded-circle img-fluid border border-dark border-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{profile.user}}">
                        {% endthumbnail %}
                    {% else %}
                        <img src="/media/profiles/no-picture.png" alt="{{profile.user}}" class="rounded-circle img-fluid border border-dark border-2" style="width: 230px;">
                    {% endif %}
                    
                    <h5 class="my-3">{{profile.first_name}} {{profile.last_name}}</h5>
                  
                    <div class="d-flex justify-content-center pb-3">
                      <div class="text-center mr-3 border-end p-2">
                          <h2>{{total_posts}}</h2>
                          <span>Posts</span>
                      </div>
                      <div class="text-center mr-3 border-start p-2">
                          <h2>{{total_followers}}</h2>
                          <span>Followers</span>
                      </div>
                    </div>
                  
                  {% if user.is_authenticated %}
                    {% if profile.user != user %}
                      <div class="d-flex justify-content-center mb-2">
                        <button type="button" 
                          class="js-follow btn {% if you_follow %}btn-danger{% else %}btn-primary{% endif %}" 
                          data-id="{{profile.user.id}}" data-action="{% if you_follow %}un-{% endif %}follow"
                          data-url="{% url 'profiles:follow' profile.user.id %}">
                          <span>
                            {% if you_follow %}
                              Unfollow
                            {% else %}
                              Follow
                            {% endif %}
                          </span>
                        </button>
                      </div>
                    {% else %}
                      <div class="d-flex justify-content-center mb-2">
                        <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-primary"
                          onclick="window.location='{% url 'profiles:picture_update' profile.id %}'">
                            {% if profile.image %}
                              Change Picture
                            {% else %}
                              Upload Picture
                            {% endif %}
                        </button>
                        {% if profile.image %}
                            <button type="submit" data-mdb-button-init data-mdb-ripple-init 
                              class="btn btn-outline-danger ms-1"
                              onclick="window.location='{% url 'profiles:picture_delete' profile.id %}'">
                              Remove Picture
                            </button>
                        {% endif %}
                      </div>
                    {% endif %}
                  {% else %}
                    <div class="d-flex justify-content-center mb-2">
                      <a class="btn btn-outline-dark m-1" href="{% url 'account_login' %}">Login to Follow</a>
                    </div>
                  {% endif %}
                  
                </div>
              </div>
            </div>

            <div class="col-lg-8">
              <div class="card mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">First Name</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{profile.first_name}}</p>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Last Name</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{profile.last_name}}</p>
                    </div>
                  </div>
                  <hr>
                  {% if user.is_authenticated and profile.user == user %}
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Username</p>
                      </div>
                      <div class="col-sm-9">
                        <p class="text-muted mb-0">{{profile.user.username}}</p>
                      </div>
                    </div>
                    <hr>
                  {% endif %}
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Email</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{profile.user.email}}</p>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Mobile</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{profile.mobile}}</p>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">Address</p>
                    </div>
                    <div class="col-sm-9">
                      <p class="text-muted mb-0">{{profile.address}}</p>
                    </div>
                  </div>
                  {% if user.is_authenticated and profile.user == user %}
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <a class="btn btn-outline-primary" href="{% url 'profiles:profile_update' profile.id %}">Update</a>
                      </div>
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
   
{% endblock content %}

profiles/templates/profiles/profile_form.html
{% extends 'base_master.html' %}
{% load django_bootstrap5 %}

{% block title %}
    Tech Blog - Update Profile
{% endblock title %}
    
{% block content %}
    <div class="container mt-3">
        <h1>Update Profile</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-outline-primary" type="submit">Update</button>
            <a class="btn btn-outline-danger" href="{% url 'profiles:profile_detail' profile.id %}">Cancel</a>
        </form>
    </div>
{% endblock content %}
        