blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'post_list'),
    path('detail/<int:pk>', views.PostDetail.as_view(), name = "post_detail"),
    path('create/', views.PostCreate.as_view(), name = "post_create"),
    path('update/<int:pk>', views.PostUpdate.as_view(), name = "post_update"),
    path('delete/<int:pk>', views.PostDelete.as_view(), name = "post_delete"),
    path('my-post-lists', views.MyPostList.as_view(), name = 'my_post_list')
]

followers/urls.py
from django.urls import path
from . import views

app_name = 'followers'

urlpatterns = [
    path("<str:user>", views.MyFollowers.as_view(), name = 'followers_list'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePage.as_view(), name = 'index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('followers/', include('followers.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path("detail/<int:pk>", views.UserProfile.as_view(), name = 'profile_detail'),
    path("update/<int:pk>", views.UpdateUserProfile.as_view(), name = 'profile_update'),
    # Update Profile Picture
    path("update/picture/<int:pk>", views.UpdateProfilePicture, name = 'picture_update'),
    # Delete Profile Picture
    path("delete/picture/<int:pk>", views.DeleteProfilePicture, name = 'picture_delete'),
    # For Followers
    path('detail/<int:pk>/follow/', views.FollowView.as_view(), name = 'follow'),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:index' %}">Tech Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav me-auto mb-2 mb-sm-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:my_post_list' %}">My Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'followers:followers_list' request.user %}">My Followers</a>
          </li>
        {% endif %}
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item" href="{% url 'blog:post_list' %}">Blog Posts</a></li>
            <li><a class="dropdown-item" href="#">Create Post</a></li>
          </ul>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
      <hr class="text-light">
      <ul class="navbar-nav mb-2 mb-sm-0">
        <li class="nav-item dropdown">
          {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
              <a class="btn btn-outline-light m-1" href="/admin" target="_blank">Django Administration</a>
            {% endif %}
            <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">Manage Account</button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'profiles:profile_detail' user.profiles.id %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'account_email' %}">Change Email Address</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="/accounts/2fa">Two-Factor Authentication</a></li>
                <li><a class="dropdown-item" href="/accounts/sessions">Sessions</a></li>
            </ul>
            <a class="btn btn-danger m-1" href="{% url 'account_logout' %}">Logout</a>
          {% else %}
            <a class="btn btn-outline-light m-1" href="{% url 'account_login' %}">Login</a>
            <a class="btn btn-warning m-1" href="{% url 'account_signup' %}">Sign Up</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>