blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'post_list'),
    path('detail/<int:pk>', views.PostDetail.as_view(), name = "post_detail"),
    path('create/', views.PostCreate.as_view(), name = "post_create"),
    path('update/<int:pk>', views.PostUpdate.as_view(), name = "post_update"),
    path('delete/<int:pk>', views.PostDelete.as_view(), name = "post_delete"),
    path('my-post-lists', views.MyPostList.as_view(), name = 'my_post_list')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('followers/', include('followers.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path("detail/<int:pk>", views.UserProfile.as_view(), name = 'profile_detail'),
    path("update/<int:pk>", views.UpdateUserProfile.as_view(), name = 'profile_update'),
    # Update Profile Picture
    path("update/picture/<int:pk>", views.UpdateProfilePicture, name = 'picture_update'),
    # Delete Profile Picture
    path("delete/picture/<int:pk>", views.DeleteProfilePicture, name = 'picture_delete'),
    # For Followers
    path('detail/<int:pk>/follow/', views.FollowView.as_view(), name = 'follow'),
]

blog/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.conf import settings

# Post Model
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(upload_to='posts', blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title[0:25]

blog/forms.py
from django.forms import ModelForm
from django.forms import ImageField, FileInput

from blog.models import Post

class PostForm(ModelForm):
    image = ImageField(widget=FileInput, label="Upload New Image")
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Post
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import PostForm
from django.contrib import messages

# Show all the list of Posts
class PostList(ListView):
    model = Post
    http_method_names = ['get']
    queryset = Post.objects.all()
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'

# Show Post Details
class PostDetail(DetailView):
    model = Post
    http_method_names = ['get']
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'
    pk_url_kwarg = 'pk'

    # To get the required post
    def get_object(self):
        queryset = get_object_or_404(self.model, id=self.kwargs['pk'])
        return queryset

# To Create a new Post
class PostCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'image']
    http_method_names = ['get', 'post']
    context_object_name = 'form'
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:post_list')
    # success_message = "Your post has been created successfully."

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, request.FILES)
        if not form.is_valid():
            context = {
                'form':form
            }
            return render(request, self.template_name, context)
        
        # Add the owner of the record
        obj = form.save(commit = False)
        obj.owner = self.request.user
        obj.save()

        messages.success(request, "Department was successfully created.")
        return redirect(self.success_url)
        
# To Update the Post
class PostUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Post
    # fields = ['title', 'content']
    form_class = PostForm
    http_method_names = ['get', 'post']
    context_object_name = 'form'
    pk_url_kwarg = 'pk'
    template_name = 'blog/post_form.html'
    # success_url = reverse_lazy('blog:post_list')
    # success_message = "Your post has been updated successfully."

    # Update Post with Image
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(self.model, id=self.kwargs['pk'])
        if post.owner == self.request.user:
            if request.FILES:
                post.image.delete() # To delete old image
            form = PostForm(request.POST, request.FILES, instance=post)
            if not form.is_valid():
                context = {
                    'form':form
                }
                return render(request, self.template_name, context)

            form.save()
            messages.success(request, "Your post has been updated successfully.")
        else:
            messages.error(request, "Your are not an author of the post.")
        return redirect(self.get_success_url())

    #  Custom Query
    def get_queryset(self):
        queryset = self.model.objects.filter(id=self.kwargs['pk'])
        return queryset
    
    # Add your context data
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(PostUpdate, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['form_type'] = 'Update'
        return context
    
    # Customize Success URL
    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk' : self.kwargs['pk']})

# To Delete a Post
class PostDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')
    http_method_names = ['get', 'post']
    pk_url_kwarg = 'pk'
    context_object_name = 'post'
    template_name = 'blog/post_confirm_delete.html'
    # success_message = "Your post has been deleted successfully."

    def get_queryset(self):
        queryset = self.model.objects.filter(id=self.kwargs['pk'])
        return queryset
    
    # Delete Post with Image
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(self.model, id=self.kwargs['pk'])
        if post.owner == self.request.user:
            post.image.delete() # To delete old image
            post.delete()
            messages.success(request, "Your post has been deleted successfully.")
        else:
            messages.error(request, "Your are not an author of the post.")
        return redirect(self.success_url)
    
# My Posts
class MyPostList(LoginRequiredMixin, ListView):
    model = Post
    http_method_names = ['get']
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'

    #  Custom Query
    def get_queryset(self):
        queryset = self.model.objects.filter(owner=self.request.user)
        return queryset

blog/templates/blog/post_confirm_delete.html
{% extends 'base_master.html' %}

{% block title %}
    Delete {{post.title}}
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        <h1>Delete Post</h1>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            <h1>Are you sure want to delete the <span class="text-danger">"{{post.title}}"</span> post ?
            <p>
                <button type="submit" class="btn btn-danger">Yes, I am sure!</button>
                <button type="button" class="btn btn-secondary"
                    onclick = "window.location='{% url 'blog:post_list' %}'">No, take me back</button>
            </p>
        </form>
    </div>
{% endblock content %}
    

blog/templates/blog/post_detail.html
{% extends 'base_master.html' %}
{% load humanize %}
{% load thumbnail %}
{% load static %}

{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
    <div class="container mt-3 mb-3">
        <div class="row justify-content-between">
            <div class="col-sm-12 col-md-8">
              <h1>{{post.title}}</h1>
            </div>
            <div class="d-none d-sm-block col-md-4">
                <div class="alert alert-info text-center" role="alert">
                    Last updated {{post.updated_at|naturaltime}}
                </div>
            </div>
        </div>
        <hr>
        <div class="clearfix">
            {% if post.image %}
                <img src="{{post.image.url}}" alt="post-image" 
                    class="img-fluid col-md-6 float-md-end mb-3 ms-md-3">
            {% else %}
                <img src="{% static 'blog/img/no-image.png' %}" alt="post-image"
                    class="img-fluid col-md-6 float-md-end mb-3 ms-md-3">
            {% endif %}
            <p>{{post.content}}</p>
            <hr>
            <div class="row justify-content-between">
                <div class="col-sm-12 col-md-6">
                    <p><span class="fw-bold">Author:</span>
                        <a href="{% url 'profiles:profile_detail' post.owner.profiles.id %}" style="text-decoration: none;">
                            {% if post.owner.profiles.image %}
                              {% thumbnail post.owner.profiles.image "30x30" crop="center" as im %}
                                <img class="img-thumbnail rounded-circle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{post.owner}}">
                              {% endthumbnail %}
                            {% else %}
                              <img class="img-thumbnail rounded-circle" src="/media/profiles/no-picture.png"  width="30" height="30" alt="{{post.owner}}">
                            {% endif %}
                            {{post.owner.profiles.first_name}} {{post.owner.profiles.last_name}}              
                        </a>
                    </p>
                </div>
                <div class="col-sm-12 col-md-6">
                    <p><span class="fw-bold">Post created on:</span> {{post.created_at|date}}</p>
                </div>
            </div>
            <hr>
            <a href="{% url 'blog:post_list' %}" class="btn btn-outline-primary"><i class="bi bi-back"></i> Back</a>
            {% if user.is_authenticated %}
                {% if post.owner == user %}
                    <a href="{% url 'blog:post_update' post.id %}" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i> Update</a>
                    <a href="{% url 'blog:post_delete' post.id %}" class="btn btn-outline-danger"><i class="bi bi-trash3"></i> Delete</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}
    

blog/templates/blog/post_form.html
{% extends 'base_master.html' %}
{% load django_bootstrap5 %}

{% block title %}
    Create a New Post
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        
        {% if form_type == 'Update' %}
            <h1>Update a Post</h1>
        {% else %}
            <h1>Create a New Post</h1>
        {% endif %}
        <hr>

        <form class="mb-3" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            
            <!-- To display existing Image while updating post -->
            {% if form_type == 'Update' and form.image.value != "" %}
                <div class="mb-3">
                    <label class="form-label" for="current_image">Current Image</label><br/>
                    <img src="/media/{{form.image.value}}" class="img-fluid" width="25%" alt="post-image">
                </div>
            {% endif %}

            <button type="submit" class="btn btn-primary">
                {% if form_type == 'Update' %}
                    Update Post
                {% else %}
                    Create Post
                {% endif %}
           </button>
            <button type="button" class="btn btn-danger" 
                onclick="window.location='{% url 'blog:post_list' %}'">Cancel</button>
        </form>
    </div>
{% endblock content %}
    
    

blog/templates/blog/post_list.html
{% extends 'base_master.html' %}
{% load static %}
{% load humanize %}
{% load sorl_thumbnail %}

{% block title %}
    Tech Blog - Posts
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        <div class="row justify-content-between">
          <div class="col-6">
            <h1>Feed</h1>
          </div>
          <div class="col-6">
            <button type="button" class="btn btn-primary float-end"
                onclick = "window.location='{% url 'blog:post_create' %}'">
              <i class="bi bi-plus-square"></i> Create Post
            </button>
          </div>
        </div>
        <hr>
        {% if post_list %}
        <!-- Start Cards Layout -->
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
            {% for post in post_list %}
            <!-- Card Start -->
            <div class="col">
              <div class="card h-100">
                {% if post.image %}
                  {% thumbnail post.image "400x256"  crop="center" as im %}
                    <img class="card-img-top" alt="{{post.title}}"
                      src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"">
                  {% endthumbnail %}
                {% else %}
                  <img src="{% static 'blog/img/no-image.png' %}" class="card-img-top" alt="no-image">
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <p class="card-text">{{post.content|truncatechars:100}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-outline-primary btn-sm">
                          <i class="bi bi-view-list"></i> View Post
                        </a>
                        {% if user.is_authenticated %}
                          {% if post.owner == user %}
                            <a href="{% url 'blog:post_update' post.id %}" class="btn btn-outline-secondary btn-sm">
                              <i class="bi bi-pencil-square"></i> Edit Post
                            </a>
                            <a href="{% url 'blog:post_delete' post.id %}" class="btn btn-outline-danger btn-sm">
                              <i class="bi bi-trash3"></i> Delete Post
                            </a>
                          {% endif %}
                        {% endif %}
                    </li>
                    <li class="list-group-item"><span class="fw-bold">Post Date : </span>{{post.created_at|date}}</li>
                    <li class="list-group-item"><span class="fw-bold">Author : </span>
                      <a href="{% url 'profiles:profile_detail' post.owner.profiles.id %}" style="text-decoration: none;">
                        {% if post.owner.profiles.image %}
                          {% thumbnail post.owner.profiles.image "30x30" crop="center" as im %}
                            <img class="img-thumbnail rounded-circle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{post.owner}}">
                          {% endthumbnail %}
                        {% else %}
                          <img class="img-thumbnail rounded-circle" src="/media/profiles/no-picture.png"  width="30" height="30" alt="{{post.owner}}">
                        {% endif %}
                        {{post.owner.profiles.first_name}} {{post.owner.profiles.last_name}}              
                      </a>
                    </li>
                </ul>
                <div class="card-footer">
                  <small class="text-body-secondary">Last updated {{post.updated_at|naturaltime}}</small>
                </div>
              </div>
            </div>
            <!-- Card End -->
            {% endfor %}
          </div>
          <!-- End Cards Layout -->
          {% else %}
            <div class="alert alert-info" role="alert">
                There are no posts in the database.
            </div>
          {% endif %}
          
        </div>
{% endblock content %}